### ISSUE TITLE
Sync server refuses connection

### ISSUE THREAD

**Issue by xrat** [denyhosts/denyhosts#53] opened 2016-05-10 16:09 UTC
I am running DenyHosts 3.1 with

```
SYNC_SERVER = http://deny.resonatingmedia.com:9911
```

but since early April 2016 all connections are refused:

```
2016-05-10 18:05:51,800 - sync        : ERROR    [Errno 111] Connection refused
```

**Comment by slicer69** [comment] 2016-05-10 16:57
The default sync server had to be taken off-line due to too much traffic.

**Comment by jasontibbitts** [comment] 2016-05-10 20:14
Is there anything someone else could do to help with this? How much traffic did it generate?  I have plenty of infrastructure and could definitely run something.

I haven't checked the sync server source but if it supports any kind of distributed operation I could probably get a couple of different nodes set up, and maybe get one in Fedora infrastructure to use as a default for the Fedora packages.

**Comment by slicer69** [comment] 2016-05-10 20:44
The sync server doesn't offer distributed infrastructure, but if you'd like to set it up I'll be happy to help you create/configure a new home for the server.

I should have clarified, it's not so much the network  traffic the service gets that is the problem, but the memory required to keep it going when it's getting hits. The sync server process used several hundred MB of memory on the virtual test server I was running, which only had 768MB of RAM. As a result, the sync server process kept bogging things down and getting killed when the VPS ran out of memory. I had to either pay for an upgrade or turn off the service.

A sever with a couple GB of RAM would probably be fine for this sort of thing.

**Comment by jasontibbitts** [comment] 2016-05-10 23:50
OK, that is really a drop in the bucket given how little of my current infrastructure I'm actually using.  I'm still kind of backed up and I still (after months) have pending denyhosts stuff to work on but I do have the resources.

I don't even know where the source for the sync server is living.  I would be really surprised if it wasn't in the main tree or in another project under github/denyhosts, but I don't see it.

**Comment by slicer69** [comment] 2016-05-10 23:55
The sync server lives in another project over here: https://github.com/janpascal/denyhosts_sync

If you like, I can send you a tarball of my configuration and source. Possibly a dump of the sync server's database up to about a month ago.

**Comment by jasontibbitts** [comment] 2016-05-11 00:13
Sure.  tibbs@math.uh.edu.

**Comment by slicer69** [comment] 2016-05-11 00:35
Sent over the configuration, code and database.

**Comment by xrat** [comment] 2016-05-12 10:52
Could this "issue" be reopened or another one created to keep track of @jasontibbitts' progress?

**Comment by slicer69** [comment] 2016-05-12 12:40
Sure thing. Jason has the code, config and database. Just going through the steps of putting all the pieces together on the new server.

**Comment by jasontibbitts** [comment] 2016-05-12 18:33
Yeah, I just have a bit more work to do.  Once done, no configuration changes should be necessary as we're just redirecting the IP to my server.

But the sync server really does need a way to communicate with other sync servers so that we can have a pool of them.

**Comment by pataquets** [comment] 2016-05-16 02:54
If all necessary files could be made available on the gh repo when is everything done, along with notes or docs, it could encourage help addition of volunteered servers and offloading current.

**Comment by slicer69** [comment] 2016-05-16 12:49
All the files are available on te sync server's GitHub page. https://github.com/janpascal/denyhosts_sync

**Comment by jasontibbitts** [comment] 2016-05-16 16:35
Didn't have a lot of time this weekend, but the software is at least installed and running.  Just some more checks before I turn off the firewall.

**Comment by jasontibbitts** [comment] 2016-05-23 19:40
That was a bit more involved than I expected, but it appears to be accepting connections currently.  The IP has been redirected and I'm seeing occasional activity.

Note: this is running 2.0.0 of the server, which is a bit updated from the version that was running previously.

Please try it out and let me know how things are working.

**Comment by slicer69** [comment] 2016-05-23 20:08
I can confirm a connection here. Unless someone else reports an issue, I think this can be closed.

**Comment by xrat** [comment] 2016-05-24 20:12
I switched back to `deny.resonatingmedia.com:9911` about 24h ago. Haven't received any data yet appart from (UTC)
```
2016-05-24 19:04:18,285 - denyhosts   : WARNING  got invalid host (127.0.0.1), ignoring
```
but also no errors or timeouts.

**Comment by janpascal** [comment] 2016-05-27 09:01
Hi, good to hear the sync server is back up. It's weird though that it should use that much memory for so few contributors. Let's see what happens if more people use the new sync server.

One thing about the new server instance: it seems the css files don't get served, maybe the "static_dir" setting isn't correct, or the "css" directory isn't where it should be.

**Comment by jasontibbitts** [comment] 2016-05-27 17:34
I'll take a look.  I thought it was supposed to look that way....

I have a whole lot of resources I can use for this thing.  The servers which host the VMs have 256GB of RAM, 10G Ethernet and no kinetic storage at all.  With the ten contributors we have I think that will be enough for a while, but it would still be nice to have some way that multiple servers can communicate with each other and a pool of servers for clients to query.  (I.e. at least two, just in case.)

**Comment by janpascal** [comment] 2016-06-08 19:18
Jason, I like your suggestion of a pool of servers. I've started implementing something, see https://github.com/janpascal/denyhosts_sync/issues/32 for the issue in the denyhosts-server project.

**Comment by janpascal** [comment] 2017-07-13 20:29
There is a new sync server at sync.denyhosts.org:9911, thanks to Adriel. Closing this issue now

**Closed by janpascal** 2017-07-13 20:29 UTC

**Comment by xrat** [comment] 2017-07-14 14:09
Is the new server officially replacing `deny.resonatingmedia.com`? It's still in `denyhosts.conf`, see https://github.com/denyhosts/denyhosts/blob/master/denyhosts.conf#L620

**Comment by jasontibbitts** [comment] 2017-07-14 16:36
I guess I will get rid of the resources to allocate to this.  It's a pity that the sync-server is so difficult to deploy; otherwise there never would have been an issue.

I guess if we do intend to implement a pool of sync servers and someone makes it reasonably easy to deploy (ie. not require the really annoying yuicompressor) then I could in the future set it back up.
